<?php
const ALU_ID = 'ALU_ID';
const ALU_NOMBRE = 'ALU_NOMBRE';
const ALU_ASIGNATURA = 'ALU_ASIGNATURA';
const ALU_TURNO = 'ALU_TURNO';
const ALU_MODIFICACION = 'ALU_MODIFICACION';
const ALU_ELIMINADO = 'ALU_ELIMINADO';
